python genComments.py x3dom_nodes/Bindable.js x3dom_nodes_commented/Bindable.js
python genComments.py x3dom_nodes/BVHRefiner.js x3dom_nodes_commented/BVHRefiner.js
python genComments.py x3dom_nodes/CADGeometry.js x3dom_nodes_commented/CADGeometry.js
python genComments.py x3dom_nodes/Core.js x3dom_nodes_commented/Core.js
python genComments.py x3dom_nodes/EnvironmentalEffects.js x3dom_nodes_commented/EnvironmentalEffects.js
python genComments.py x3dom_nodes/Followers.js x3dom_nodes_commented/Followers.js
python genComments.py x3dom_nodes/Geometry2D.js x3dom_nodes_commented/Geometry2D.js
python genComments.py x3dom_nodes/Geometry3D.js x3dom_nodes_commented/Geometry3D.js
python genComments.py x3dom_nodes/Geometry3DExt.js x3dom_nodes_commented/Geometry3DExt.js
python genComments.py x3dom_nodes/Geospatial.js x3dom_nodes_commented/Geospatial.js
python genComments.py x3dom_nodes/Grouping.js x3dom_nodes_commented/Grouping.js
python genComments.py x3dom_nodes/HAnim.js x3dom_nodes_commented/HAnim.js
python genComments.py x3dom_nodes/Interpolation.js x3dom_nodes_commented/Interpolation.js
python genComments.py x3dom_nodes/Lighting.js x3dom_nodes_commented/Lighting.js
python genComments.py x3dom_nodes/Navigation.js x3dom_nodes_commented/Navigation.js
python genComments.py x3dom_nodes/Networking.js x3dom_nodes_commented/Networking.js
python genComments.py x3dom_nodes/NodeNameSpace.js x3dom_nodes_commented/NodeNameSpace.js
python genComments.py x3dom_nodes/Rendering.js x3dom_nodes_commented/Rendering.js
python genComments.py x3dom_nodes/Shaders.js x3dom_nodes_commented/Shaders.js
python genComments.py x3dom_nodes/Shape.js x3dom_nodes_commented/Shape.js
python genComments.py x3dom_nodes/Sound.js x3dom_nodes_commented/Sound.js
python genComments.py x3dom_nodes/Text.js x3dom_nodes_commented/Text.js
python genComments.py x3dom_nodes/Texturing.js x3dom_nodes_commented/Texturing.js
python genComments.py x3dom_nodes/Texturing3D.js x3dom_nodes_commented/Texturing3D.js
python genComments.py x3dom_nodes/Time.js x3dom_nodes_commented/Time.js
python genComments.py x3dom_nodes/VolumeRendering.js x3dom_nodes_commented/VolumeRendering.js
