User's Guide
------------
This part of the documentation, which is mostly prose, begins with some
basic information about X3DOM, then focuses on step-by-step
instructions for building applications with X3DOM.

.. toctree::
   :maxdepth: 2

   gettingstarted
   navigation
   tutorial
   configuration
   api
   troubleshooting


Additional Notes
----------------
Design notes, legal information and changelog are here for the interested.

.. toctree::
   :maxdepth: 2

   notes/index
   releasenotes
   license
