User's Guide
------------

This part of the documentation, which is mostly prose, begins with some
background information about X3DOM, then focuses on step-by-step
instructions for web development with X3DOM.

.. toctree::
   :maxdepth: 2

   gettingstarted
   tutorial
   troubleshooting

API Reference
-------------

If you are looking for information on a specific function, class or
method, this part of the documentation is for you.

.. toctree::
   :maxdepth: 2

   api

Additional Notes
----------------

Design notes, legal information and changelog are here for the interested.

.. toctree::
   :maxdepth: 2

   notes/index
   releasenotes
   license
